name: Test package

on:
  push:
    # The CI is executed on every push on every branch
    branches:
      - main
  pull_request:
    # The CI is executed on every pull request to the main branch
    branches:
      - main

  schedule:
    # The CI is executed every day at 8am
    - cron: "0 8 * * *"
jobs:

  create-datasets:
    runs-on: "ubuntu-22.04"
    container: ghcr.io/scientificcomputing/fenics:test_2023.1.0

    env:
      data_dir: "legacy"

    steps:
      - uses: actions/checkout@v3

      - name: Create datasets
        run: python3 ./tests/create_legacy_data.py --output-dir=$data_dir

      - uses: actions/upload-artifact@v3
        with:
          name: ${{ env.data_dir }}
          path: ./${{ env.data_dir }}

  test-code:
    runs-on: "ubuntu-22.04"
    needs: create-datasets
    container: "dolfinx/dolfinx:nightly"

    env: 
      DEB_PYTHON_INSTALL_LAYOUT: deb_system
      PYTHONPATH: /usr/local/lib/python3/dist-packages:/usr/local/lib:/usr/local/dolfinx-real/lib/python3.10/dist-packages
    steps:
      - uses: actions/checkout@v3

      - name: Update pip
        run: python3 -m pip install --upgrade pip setuptools

      - uses: actions/download-artifact@v3
        with:
          name: ${{ env.data_dir }}
          path: tests/

      - name: Install package
        run: python3 -m pip install .[test]

      - name: Run tests
        run: python3 -m pytest

      - name: 
        run: ls tests/
